USE UNLAM_Progra_Web_2_Trabajo_Practico_Final;

SET sql_safe_updates=0;

DELETE FROM usuario;
DELETE FROM administrador;
DELETE FROM catalogo;
DELETE FROM catalogo_lector;
DELETE FROM catalogo_suscriptor;
DELETE FROM comentario;
DELETE FROM contenidista;
DELETE FROM domicilio;
DELETE FROM factura;
DELETE FROM interaccion;
DELETE FROM interaccion_comentario;
DELETE FROM lector;
DELETE FROM localidad;
DELETE FROM medio_pago;
DELETE FROM noticia;
DELETE FROM noticia_contenido;
DELETE FROM pago;
DELETE FROM permiso;
DELETE FROM provincia;
DELETE FROM publicacion;
DELETE FROM reaccion;
DELETE FROM seccion;
DELETE FROM suscripcion;
DELETE FROM suscriptor;
DELETE FROM tipo_doc;
DELETE FROM tipo_factura;
DELETE FROM tipo_publicacion;
DELETE FROM tipo_reaccion;
DELETE FROM tipo_suscripcion;
